zram-swap: default to lzo instead of lzo-rle compression

diff --git a/package/system/zram-swap/files/zram.init b/package/system/zram-swap/files/zram.init
--- a/package/system/zram-swap/files/zram.init
+++ b/package/system/zram-swap/files/zram.init
@@ -35,17 +35,17 @@ zram_applicable()
 		return 1
 	}
 
-	which mkswap >/dev/null || {
+	command -v mkswap >/dev/null || {
 		logger -s -t zram_applicable -p daemon.err "[ERROR] 'mkswap' not installed"
 		return 1
 	}
 
-	which swapon >/dev/null || {
+	command -v swapon >/dev/null || {
 		logger -s -t zram_applicable -p daemon.err "[ERROR] 'swapon' not installed"
 		return 1
 	}
 
-	which swapoff >/dev/null || {
+	command -v swapoff >/dev/null || {
 		logger -s -t zram_applicable -p daemon.err "[ERROR] 'swapoff' not installed"
 		return 1
 	}
@@ -85,8 +85,9 @@ zram_comp_algo()
 	local dev="$1"
 	local zram_comp_algo="$( uci -q get system.@system[0].zram_comp_algo )"
 
-	if [ -z "$zram_comp_algo" ] || [ ! -e /sys/block/$( basename $dev )/comp_algorithm ]; then
-		return 0
+	if [ -z "$zram_comp_algo" ]; then
+		# lzo-rle fails on small RAM devices, default to lzo, which is always available
+		zram_comp_algo="lzo"
 	fi
 
 	if [ $(grep -c "$zram_comp_algo" /sys/block/$( basename $dev )/comp_algorithm) -ne 0 ]; then
